---
nats_version: "2.10.7"
nats_user: nats
nats_group: nats
nats_config_dir: /etc/nats
nats_data_dir: /var/lib/nats
nats_log_dir: /var/log/nats

# TLS configuration
nats_tls_enabled: true
nats_tls_cert_file: /etc/nats/certs/server-cert.pem
nats_tls_key_file: /etc/nats/certs/server-key.pem
nats_tls_ca_file: /etc/nats/certs/ca.pem

# Authentication
nats_auth_enabled: true
nats_auth_token: "{{ vault_nats_auth_token }}"  # Store this in ansible-vault

# Cluster configuration
nats_cluster_name: "prod-cluster"
nats_cluster_routes: []  # Will be populated dynamically

# Monitoring configuration
nats_monitoring_enabled: true
nats_monitoring_port: 8222

# group_vars/all.yml
custom_ca_cert: "my-custom-ca.pem"
custom_server_cert: "my-server.pem"
custom_server_key: "my-key.pem"