---
- name: Deploy NATS Cluster
  hosts: nats_cluster
  become: yes
  gather_facts: no  # Disable initial fact gathering

  pre_tasks:
    - name: Install Python 3
      raw: |
        if [ -f /etc/debian_version ]; then
          apt-get update && apt-get install -y python3 python3-pip
        elif [ -f /etc/redhat-release ]; then
          dnf install -y python3 python3-pip
        fi
      changed_when: false

    - name: Set python interpreter path
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"

    - name: Gather facts
      setup:

  roles:
    - certificates
    - common
    - nats