---
- name: Deploy NATS Cluster
  hosts: nats_cluster
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Install Python and dependencies
      raw: |
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update
          apt-get install -y python3 python3-pip python3-setuptools
        elif command -v dnf >/dev/null 2>&1; then
          dnf install -y python3 python3-pip python3-setuptools
        fi
      changed_when: false

    - name: Set python interpreter path
      set_fact:
        ansible_python_interpreter: "/usr/bin/python3"

    - name: Gather facts
      setup:

  roles:
    - common
    - certificates
    - nats