---
- name: Download NATS Server
  get_url:
    url: "https://github.com/nats-io/nats-server/releases/download/v{{ nats_version }}/nats-server-v{{ nats_version }}-linux-amd64.zip"
    dest: /tmp/nats-server.zip
    mode: 0644

- name: Extract NATS Server
  unarchive:
    src: /tmp/nats-server.zip
    dest: /tmp
    remote_src: yes

- name: Install NATS Server binary
  copy:
    src: "/tmp/nats-server-v{{ nats_version }}-linux-amd64/nats-server"
    dest: /usr/local/bin/nats-server
    mode: 0755
    remote_src: yes

- name: Configure NATS Server
  template:
    src: nats-server.conf.j2
    dest: "{{ nats_config_dir }}/nats-server.conf"
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: 0640
  notify: restart nats

- name: Install systemd service
  template:
    src: nats.service.j2
    dest: /etc/systemd/system/nats.service
    mode: 0644
  notify: restart nats

- name: Enable and start NATS service
  systemd:
    name: nats
    state: started
    enabled: yes
    daemon_reload: yes

