# roles/common/tasks/main.yml
---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required packages
  package:
    name:
      - curl
      - unzip
      - jq
    state: present

- name: Create NATS group
  group:
    name: "{{ nats_group }}"
    state: present
    system: yes

- name: Create NATS user
  user:
    name: "{{ nats_user }}"
    group: "{{ nats_group }}"
    system: yes
    create_home: no
    shell: /sbin/nologin
    state: present

- name: Create NATS directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nats_user }}"
    group: "{{ nats_group }}"
    mode: 0750
  with_items:
    - "{{ nats_config_dir }}"
    - "{{ nats_data_dir }}"
    - "{{ nats_log_dir }}"